# This is a standard ActiveRecord database.yml file. You can configure it 
# to use any database that ActiveRecord supports. Only the central server needs
# this file to be configured -- nodes never connect directly to the database.

:adapter:  postgresql
:encoding: unicode
:host:   localhost
:database: cloud_crowd
allow_concurrency: true

# If you'd prefer to use an SQLite database instead, the following configuration
# will do nicely:
#
# :adapter:  sqlite3
# :database: cloud_crowd.db
